/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddEventDialog: typeof import('./../src/views/dashboard/components/AddEventDialog.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    CreateTaskDialog: typeof import('./../src/views/kanban/components/CreateTaskDialog.vue')['default']
    DatePicker: typeof import('./../src/views/dashboard/components/DatePicker.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EventCard: typeof import('./../src/views/dashboard/components/EventCard.vue')['default']
    EventInfo: typeof import('./../src/views/dashboard/components/EventInfo.vue')['default']
    EventsCalendar: typeof import('./../src/views/dashboard/components/EventsCalendar.vue')['default']
    FF: typeof import('./../src/components/FF.vue')['default']
    GoogleMap: typeof import('./../src/views/dashboard/components/GoogleMap.vue')['default']
    Header: typeof import('./../src/components/layout/Header.vue')['default']
    KanbanItem: typeof import('./../src/views/kanban/components/KanbanItem.vue')['default']
    KanbanRow: typeof import('./../src/views/kanban/components/KanbanRow.vue')['default']
    MenuIcon: typeof import('./../src/components/components/MenuIcon.vue')['default']
    MobileMenu: typeof import('./../src/components/components/MobileMenu.vue')['default']
    PreviewModal: typeof import('./../src/views/galery/components/PreviewModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskInfoDialog: typeof import('./../src/views/kanban/components/TaskInfoDialog.vue')['default']
    UserEventsList: typeof import('./../src/views/dashboard/components/UserEventsList.vue')['default']
  }
}
